import { Geist, Geist_Mono } from "next/font/google";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps
} from '@mantine/core';
import "@mantine/core/styles.css";
import "./globals.css";
import MantineShell from "@/components/MantineShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      /* className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} */
      {...mantineHtmlProps}
    >
      <head>
        <ColorSchemeScript />
      </head>
      <body /* className="min-h-full flex flex-col" */>
        <MantineProvider>
          <MantineShell>
            {children}
          </MantineShell>
        </MantineProvider>
      </body>
    </html>
  );
}
